version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    env_file:
      - app.env
    ports:
      - "3000:3000"
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ./:/app:delegated
    depends_on:
      - "db"
    container_name: web
    restart: always
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - app.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    container_name: db
  generate-models:
    build:
      context: .
      dockerfile: Dockerfile-models
    depends_on:
      - "db"
    command: sqlboiler psql --add-global-variants
    volumes:
      - ./:/app
    container_name: "generate-models"
    restart: "no"
    profiles:
    - manual
volumes:
  postgres-db:
