version: '3.9'

services:
  web-with-air:
    image: cosmtrek/air
    # working_dir value has to be the same of mapped volume
    working_dir: /app
    ports:
      - 3000:3000
   # environment:
   #   - POSTGRES_USER=${POSTGRES_USER}
   #   - POSTGRES_DB=${POSTGRES_DB}
   #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
   #   - MIGRATION_PATH=${MIGRATION_PATH}
    volumes:
      - ./:/app
    container_name: web-with-air
    depends_on:
      - "db"
    profiles:
      - air
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - app.env
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:delegated
    depends_on:
      - "db"
    container_name: web
    restart: always
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - app.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    container_name: db
  generate-models:
    build:
      context: .
    depends_on:
      - "db"
      - "web"
    command: sqlboiler psql
    volumes:
      - ./:/app
    container_name: "generate-models"
    restart: "no"
    profiles:
    - manual
volumes:
  postgres-db:
